spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/internal_affairs
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:/db/migration
    validate-on-migrate: true
jwt:
  token:
    time: 86400000  # JWT tokenning amal qilishi uchun berilgan vaqt (milisekundlar bilan belgilanadi).
