-- create default region
INSERT INTO d_region(status, created_date,name,parent_id)
VALUES
    ('CREATED', Now(), 'Xalqobod',1),
    ('CREATED', Now(), 'Jizzaxlik',1),
    ('CREATED', Now(), 'Uchariq',1),
    ('CREATED', Now(), 'Ravallik',1),
    ('CREATED', Now(), 'O`ratepalik',1),
    ('CREATED', Now(), 'Olmazor',1),
    ('CREATED', Now(), 'Zilol',1),
    ('CREATED', Now(), 'Qassoblik',1),
    ('CREATED', Now(), 'Oqqo`rg`onlik',1),
    ('CREATED', Now(), 'Zargarlik',1),
    ('CREATED', Now(), 'Sayiljoyi',1),
    ('CREATED', Now(), 'Bog`ishamol',1),
    ('CREATED', Now(), 'A.Temur',1),
    ('CREATED', Now(), 'Navro`z',1),
    ('CREATED', Now(), 'Toshloq',1),
    ('CREATED', Now(), 'Shodlik',1),
    ('CREATED', Now(), 'Turon',1),
    ('CREATED', Now(), 'Sangzor',1),
    ('CREATED', Now(), 'Knmyogar',1),
    ('CREATED', Now(), 'Madaniyat',1),
    ('CREATED', Now(), 'Tinchlik',1),
    ('CREATED', Now(), 'Obod',1),
    ('CREATED', Now(), 'H.Olimjon',1),
    ('CREATED', Now(), 'A.Navoiy',1),
    ('CREATED', Now(), 'Hayrabod',1),
    ('CREATED', Now(), 'Sayxon',1),
    ('CREATED', Now(), 'Ittifoq',1),
    ('CREATED', Now(), 'Yoshlik',1),
    ('CREATED', Now(), 'Bobur',1),
    ('CREATED', Now(), 'Qaliya',1),
    ('CREATED', Now(), 'Bunyotkor',1),
    ('CREATED', Now(), 'Dustlik',1),
    ('CREATED', Now(), 'Nurliobod',1),
    ('CREATED', Now(), 'Ulug`bek',1)